on:
  push:
    branches: [main]
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - 'Dockerfile'
      - '.github/workflows/build.yaml'
  pull_request:
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - 'Dockerfile'
      - '.github/workflows/build.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: make build VERSION=${{ github.ref_name }}
      - run: git diff --exit-code go.mod go.sum
      - run: make test
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.txt

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11
      - run: go run golang.org/x/tools/cmd/deadcode@latest -test ./...
